[package]
name = "gls"
version = "0.1.0"
authors = ["Joel Uckelman <uckelman@nomic.net>"]
description = "Vassal Game Library Service"
license = "GPL-3.0-or-later"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "^0.6", features = ["headers", "http1", "json", "macros", "query", "tokio"] }
chrono = "^0.4"
base64 = "^0.21"
jsonwebtoken = "^9"
semver = "^1"
serde = { version = "^1", features = ["derive"] }
sqlx = { version = "^0.7", features = ["macros", "migrate", "runtime-tokio", "sqlite"] }
tokio = { version = "^1", features = ["full"] }
tower = { version = "^0.4", features = ["buffer", "limit"] }
# tower-http ^0.5 requires http ^1, which is not compatible with axum yet
tower-http = { version = "^0.4", features = ["cors"] }

[dev-dependencies]
# hyper ^1 requires http ^1, which is not compatible with axum yet
hyper = { version = "^0.14", features = ["full"] }
mime = "^0.3"
once_cell = "^1"
serde_json = "^1"
