[package]
name = "gls"
version = "0.1.0"
authors = ["Joel Uckelman <uckelman@nomic.net>"]
description = "Vassal Game Library Service"
license = "GPL-3.0-or-later"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "^0.7", features = ["http1", "http2", "json", "macros", "multipart", "query", "tokio"] }
axum-extra = { version = "^0.9", features = ["typed-header"] }
base64 = "^0.21"
chrono = "^0.4"
csv = "^1.3"
futures = "^0.3"
futures-util = "^0.3"
jsonwebtoken = "^9"
regex = "1.10.4"
semver = "^1"
serde = { version = "^1", features = ["derive"] }
sqlx = { version = "^0.7", features = ["macros", "migrate", "runtime-tokio", "sqlite"] }
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
thiserror = "^1"
tokio = { version = "^1", features = ["full"] }
tokio-util = "^0.7"
tower = { version = "^0.4", features = ["buffer", "limit"] }
tower-http = { version = "^0.5", features = ["compression-br", "compression-deflate", "compression-gzip", "compression-zstd", "cors", "fs"] }
unwrap-infallible = "^0.1"
zip = "0.6.6"

[dev-dependencies]
mime = "^0.3"
once_cell = "^1"
serde_json = "^1"
