[package]
name = "gls"
version = "0.1.0"
authors = ["Joel Uckelman <uckelman@nomic.net>"]
description = "Vassal Game Library Service"
license = "GPL-3.0-or-later"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "*", features = ["headers", "http1", "json", "macros", "tokio"] }
base64 = "*"
const_format = "*"
jsonwebtoken = "*"
#mime = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
sqlx = { version = "*", features = ["runtime-tokio", "macros", "sqlite"] }
tokio = { version = "*", features = ["full"] }
#tower = { version = "*", features = ["buffer", "limit"] }

[dev-dependencies]
#hyper = { version = "*", features = ["full"] }
