COMMIT TRANSACTION;
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

CREATE TABLE tmp (
  publisher_id INTEGER PRIMARY KEY NOT NULL CHECK(publisher_id >= 0),
  name TEXT NOT NULL,
  UNIQUE(name)
);

INSERT INTO tmp SELECT * FROM publishers;

DROP TABLE publishers;
ALTER TABLE tmp RENAME TO publishers;

COMMIT TRANSACTION;
PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;
